language:
  python

addons:
  apt:
    packages:
      - mobile-broadband-provider-info

python:
  - "3.5"
  - "3.6"

script: travis/ci.sh

install:
  - pip install codecov

after_success:
  - codecov

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-webapp
      tags: true
      python: "3.6"
