language:
  python

python:
  - "3.6"

sudo: required

services:
  - docker

script: travis/ci.sh

install:
  - pip install codecov

after_success:
  - codecov

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-webapp
      tags: true
