language: python

python:
  - "3.6"

sudo: required

services:
  - docker

cache: pip

before_script: make start

script: travis/ci.sh

after_script: make stop

install:
  - pip install codecov

after_success:
  - codecov

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-cloudserver
      tags: true
