language: minimal

env:
  matrix:
    - LOKOLE_QUEUE_BROKER_SCHEME=azureservicebus
    - LOKOLE_QUEUE_BROKER_SCHEME=pyamqp

services:
  - docker

install:
  - make build verify-build

before_script:
  - docker-compose up -d

script:
  - make integration-tests

after_failure:
  - docker-compose logs

after_script:
  - docker-compose down --volumes

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-cloudserver
      tags: true
