language: minimal

env:
  matrix:
    - LOKOLE_QUEUE_BROKER_SCHEME=azureservicebus
    - LOKOLE_QUEUE_BROKER_SCHEME=amqp

services:
  - docker

before_install:
  - |
    sudo curl -fsSL "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    docker-compose version

script:
  - |
    if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      make renew-cert
    else
      echo "Skipping cert renewal for on-demand build"
    fi
    if [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && [[ "$LOKOLE_QUEUE_BROKER_SCHEME" = "azureservicebus" ]]; then
      echo "Skipping live service test for branch build"
    else
      make build verify-build
      make start
      make integration-tests
    fi

after_success:
  - |
    if [[ "$LOKOLE_QUEUE_BROKER_SCHEME" = "amqp" ]]; then
      bash <(curl -s https://codecov.io/bash)
    fi

after_failure:
  - ALL=true make logs

after_script:
  - make stop

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script: DOCKER_TAG="$TRAVIS_TAG" make release deploy
    on:  # yamllint disable rule:truthy
      repo: ascoderu/opwen-cloudserver
      tags: true
      condition: $LOKOLE_QUEUE_BROKER_SCHEME = azureservicebus
