language:
  python

python:
  - "3.6"

sudo: required

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

script: travis/ci.sh

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-webapp
      tags: true
