language: minimal

env:
  matrix:
    - LOKOLE_QUEUE_BROKER_SCHEME=azureservicebus
    - LOKOLE_QUEUE_BROKER_SCHEME=amqp

services:
  - docker

script:
  - |
    if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      make renew-cert
    else
      echo "Skipping cert renewal for on-demand build"
    fi
    if [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && [[ "$LOKOLE_QUEUE_BROKER_SCHEME" = "azureservicebus" ]]; then
      echo "Skipping live service test for branch build"
    else
      make build verify-build
      make start
      make integration-tests
    fi

after_failure:
  - ALL=true make logs

after_script:
  - make stop

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script: DOCKER_TAG="$TRAVIS_TAG" make release deploy
    on:  # yamllint disable rule:truthy
      repo: ascoderu/opwen-cloudserver
      tags: true
      condition: $LOKOLE_QUEUE_BROKER_SCHEME = azureservicebus
