language: minimal

services:
  - docker

install: make build

before_script: make start

script: make integration-tests

after_script: make stop

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-cloudserver
      tags: true
