language: node_js

node_js:
  - 12

cache: yarn

install: yarn install
script: yarn run lint

before_deploy:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: master
