language: python

python:
  - "3.6"

sudo: required

services:
  - docker

cache: pip

before_script:
  - docker-compose build
  - docker-compose pull || true
  - docker-compose up -d

script: travis/ci.sh

after_script: docker-compose down --volumes

install:
  - pip install codecov

after_success:
  - codecov

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-cloudserver
      tags: true
