language:
  python

python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

env:
  - TARGET=lint
  - TARGET=unit-tests

script: make $TARGET -e py_env=~/virtualenv/python$TRAVIS_PYTHON_VERSION
