language: minimal

env:
  matrix:
    - TEST_MODE=live
    - TEST_MODE=local

services:
  - docker

before_install: ./.travis.sh before_install
install: ./.travis.sh install

before_script: export TRAVIS_SCRIPT_UUID="$(cat /proc/sys/kernel/random/uuid)"
script: ./.travis.sh script
after_success: ./.travis.sh after_success
after_failure: ./.travis.sh after_failure
after_script: ./.travis.sh after_script

before_deploy: ./.travis.sh before_deploy
deploy:
  - provider: script
    script: ./.travis.sh deploy
    on:  # yamllint disable rule:truthy
      repo: ascoderu/opwen-cloudserver
      tags: true
