language:
  python

addons:
  apt:
    packages:
      - mobile-broadband-provider-info

python:
  - "3.5"
  - "3.6"

sudo: required

before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  - . ~/.nvm/nvm.sh --no-use
  - nvm install 8.10.0
  - nvm use 8.10.0
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends yarn

script: travis/ci.sh

install:
  - pip install codecov

after_success:
  - codecov

deploy:
  - provider: script
    script: travis/cd.sh
    on:
      repo: ascoderu/opwen-webapp
      tags: true
      python: "3.6"
