version: '3.3'

services:

  nginx:
    image: ${DOCKER_REPO}/opwenserver_nginx:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT}:80
    environment:
      DNS_RESOLVER: 127.0.0.11
      HOSTNAME_CLIENT_READ: api
      HOSTNAME_CLIENT_WRITE: api
      HOSTNAME_EMAIL_RECEIVE: api
    depends_on:
      - api

  api:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CELERY_BROKER_URL: pyamqp://guest:guest@rabbitmq
      CONNEXION_SPEC: opwen_email_server/static/email-receive-spec.yaml,opwen_email_server/static/client-read-spec.yaml,opwen_email_server/static/client-write-spec.yaml
      DOTENV_SECRETS: azure;sendgrid
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
    secrets:
    - azure
    - sendgrid

  worker:
    image: ${DOCKER_REPO}/opwenserver_worker:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    environment:
      CELERY_BROKER_URL: pyamqp://guest:guest@rabbitmq
      CELERY_WORKERS: ${CELERY_WORKERS}
      DOTENV_SECRETS: azure;sendgrid
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
    secrets:
      - azure
      - sendgrid

  rabbitmq:
    image: rabbitmq:3.7.8-management

secrets:
  azure:
    file: ./secrets/azure.env
  sendgrid:
    file: ./secrets/sendgrid.env
