version: '3.3'

services:

  nginx:
    image: ${DOCKER_REPO}/opwenserver_nginx:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT}:80
    environment:
      DNS_RESOLVER: 127.0.0.11
    depends_on:
      - apiemailreceive
      - apiclientwrite
      - apiclientread

  apiemailreceive:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CONNEXION_SPEC: opwen_email_server/static/email-receive-spec.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

  apiclientwrite:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CONNEXION_SPEC: opwen_email_server/static/client-write-spec.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

  apiclientread:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CONNEXION_SPEC: opwen_email_server/static/client-read-spec.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

  apisendoutboundemails:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CONNEXION_SPEC: opwen_email_server/static/send-outbound-emails.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

  apistoreinboundemails:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CONNEXION_SPEC: opwen_email_server/static/store-inbound-emails.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

  apistorewrittenclientemails:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CONNEXION_SPEC: opwen_email_server/static/store-written-emails.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

  connectorsendoutboundemails:
    image: ${DOCKER_REPO}/opwenserver_queueconnector:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/queueconnector/Dockerfile
    environment:
      LOKOLE_POST_URL: http://apisendoutboundemails/job/email/outbound/send
      LOKOLE_SOURCE_QUEUE: sengridoutboundemails
      DOTENV_SECRETS: azure
    secrets:
      - azure
    depends_on:
      - apisendoutboundemails

  connectorstoreinboundemails:
    image: ${DOCKER_REPO}/opwenserver_queueconnector:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/queueconnector/Dockerfile
    environment:
      LOKOLE_POST_URL: http://apistoreinboundemails/job/email/inbound/store
      LOKOLE_SOURCE_QUEUE: sengridinboundemails
      DOTENV_SECRETS: azure
    secrets:
      - azure
    depends_on:
      - apistoreinboundemails

  connectorstorewritteclientemails:
    image: ${DOCKER_REPO}/opwenserver_queueconnector:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/queueconnector/Dockerfile
    environment:
      LOKOLE_POST_URL: http://apistorewrittenclientemails/job/email/client/store
      LOKOLE_SOURCE_QUEUE: lokoleinboundemails
      DOTENV_SECRETS: azure
    secrets:
      - azure
    depends_on:
      - apistorewrittenclientemails

secrets:
  azure:
    file: ./secrets/azure.env
  sendgrid:
    file: ./secrets/sendgrid.env
