version: '3.4'

x-shared-secret-environment:
  &shared-secret-environment
  build:
    args:
      USE_DEVTOOLS: "False"
  environment:
    DOTENV_SECRETS: azure;sendgrid
    LOKOLE_STORAGE_PROVIDER: AZURE_BLOBS
    QUEUE_BROKER_SCHEME: azureservicebus
  secrets:
  - azure
  - sendgrid

services:

  api:
    << : *shared-secret-environment

  worker:
    << : *shared-secret-environment

secrets:
  azure:
    file: ./secrets/azure.env
  sendgrid:
    file: ./secrets/sendgrid.env
