version: '3'

services:

  nginx:
    image: cwolff/opwenclient_nginx:${BUILD_TAG}
    build:
      context: docker/nginx
      args:
        CLIENT_VERSION: ${BUILD_TAG}
    depends_on:
      - app
    ports:
      - ${APP_PORT}:80

  app:
    image: cwolff/opwenclient_app:${BUILD_TAG}
    build:
      context: docker/app
      args:
        CLIENT_VERSION: ${BUILD_TAG}
    ports:
      - 5000:5000
    env_file:
      - ${SECRETS_FILE}
    volumes:
      - ${STATE_DIR}:/state
