version: '3'

services:

  nginx:
    image: ${DOCKER_REPO}/opwenserver_nginx:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT}:80
    environment:
      DNS_RESOLVER: 127.0.0.11
    depends_on:
      - apiemailreceive
      - apiclientwrite
      - apiclientread

  apiemailreceive:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      API_NAME: opwen_email_server/static/email-receive-spec.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
    env_file:
      - ./secrets/azure.env
      - ./secrets/sendgrid.env

  apiclientwrite:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      API_NAME: opwen_email_server/static/client-write-spec.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
    env_file:
      - ./secrets/azure.env
      - ./secrets/sendgrid.env

  apiclientread:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      API_NAME: opwen_email_server/static/client-read-spec.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
    env_file:
      - ./secrets/azure.env
      - ./secrets/sendgrid.env

  apisendoutboundemails:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      API_NAME: opwen_email_server/static/send-outbound-emails.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
    env_file:
      - ./secrets/azure.env
      - ./secrets/sendgrid.env

  apistoreinboundemails:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      API_NAME: opwen_email_server/static/store-inbound-emails.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
    env_file:
      - ./secrets/azure.env
      - ./secrets/sendgrid.env

  apistorewritteclientemails:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      JOB_NAME: opwen_email_server/static/store-written-emails.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
    env_file:
      - ./secrets/azure.env
      - ./secrets/sendgrid.env
