version: '3.3'

services:

  nginx:
    image: ${DOCKER_REPO}/opwenserver_nginx:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${APP_PORT}:80
    environment:
      DNS_RESOLVER: 127.0.0.11
    depends_on:
      - apiemailreceive
      - apiclientwrite
      - apiclientread

  apiemailreceive:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CONNEXION_SPEC: opwen_email_server/static/email-receive-spec.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

  apiclientwrite:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CONNEXION_SPEC: opwen_email_server/static/client-write-spec.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

  apiclientread:
    image: ${DOCKER_REPO}/opwenserver_api:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    environment:
      CONNEXION_SPEC: opwen_email_server/static/client-read-spec.yaml
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

  worker:
    image: ${DOCKER_REPO}/opwenserver_worker:${BUILD_TAG}
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    environment:
      LOKOLE_LOG_LEVEL: ${LOKOLE_LOG_LEVEL}
      CELERY_WORKERS: ${CELERY_WORKERS}
      DOTENV_SECRETS: azure;sendgrid
    secrets:
      - azure
      - sendgrid

secrets:
  azure:
    file: ./secrets/azure.env
  sendgrid:
    file: ./secrets/sendgrid.env
