apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-api
  name: {{ .Release.Name }}-api
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
      - name: api
        image: {{.Values.version.imageRegistry}}/opwenserver_app:{{.Values.version.dockerTag}}
        command: ["/app/run-gunicorn.sh"]
        env:
        - name: CONNEXION_SPEC
          value: dir:/app/opwen_email_server/swagger
        - name: SERVER_WORKERS
          value: "{{.Values.server.serverWorkers}}"
        {{ include "opwen.environment.shared" . }}
        - name: LOKOLE_CLOUDFLARE_USER
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: LOKOLE_CLOUDFLARE_USER
        - name: LOKOLE_CLOUDFLARE_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: LOKOLE_CLOUDFLARE_KEY
        - name: REGISTRATION_USERNAME
          valueFrom:
            secretKeyRef:
              name: users
              key: REGISTRATION_USERNAME
        - name: REGISTRATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users
              key: REGISTRATION_PASSWORD
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      restartPolicy: Always
status: {}
