apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: apistoreinboundemails
spec:
  maxReplicas: {{.Values.autoscale.maxPods}}
  minReplicas: {{.Values.autoscale.minPods}}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: apistoreinboundemails
  targetCPUUtilizationPercentage: {{.Values.autoscale.cpuThreshold}}
