apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file=compose.yml --chart
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - name: api
        image: {{.Values.version.imageRegistry}}/opwenserver_app:{{.Values.version.dockerTag}}
        command: ["/app/run-gunicorn.sh"]
        env:
        - name: CONNEXION_SPEC
          value: /app/opwen_email_server/swagger/email-receive.yaml,/app/opwen_email_server/swagger/client-read.yaml,/app/opwen_email_server/swagger/client-write.yaml,/app/opwen_email_server/swagger/client-register.yaml,/app/opwen_email_server/swagger/healthcheck.yaml
        - name: SERVER_WORKERS
          value: "{{.Values.server.serverWorkers}}"
        {{ include "opwen.environment.shared" }}
        - name: LOKOLE_CLOUDFLARE_USER
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: LOKOLE_CLOUDFLARE_USER
        - name: LOKOLE_CLOUDFLARE_ZONE
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: LOKOLE_CLOUDFLARE_ZONE
        - name: LOKOLE_CLOUDFLARE_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: LOKOLE_CLOUDFLARE_KEY
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
