apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-flower
  name: {{ .Release.Name }}-flower
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: {{ .Release.Name }}-flower
status:
  loadBalancer: {}
