apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file=compose.yml --chart
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-nginx
  name: {{ .Release.Name }}-nginx
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    io.kompose.service: {{ .Release.Name }}-nginx
status:
  loadBalancer: {}
