apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-webapp
  name: {{ .Release.Name }}-webapp
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webapp
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-webapp
    spec:
      containers:
      - name: webapp
        image: {{.Values.version.imageRegistry}}/opwenwebapp:{{.Values.version.dockerTag}}
        env:
        {{ include "opwen.environment.shared" . }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always
status: {}
