apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file=compose.yml --chart
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - name: worker
        image: {{.Values.version.imageRegistry}}/opwenserver_app:{{.Values.version.dockerTag}}
        command: ["/app/run-celery.sh"]
        env:
        - name: QUEUE_WORKERS
          value: "{{.Values.worker.queueWorkers}}"
        {{ include "opwen.environment.shared" }}
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
