swagger: '2.0'

info:
  title: Opwen Cloudserver Email API.
  version: '0.1'

basePath: '/api/email/upload'

paths:

  '/{client_id}':

    post:
      operationId: opwen_email_server.integration.connexion.client_write
      summary: Endpoint where Lokole clients notify the server that they wish to send/upload some emails.
      consumes:
        - application/json
      parameters:
        - $ref: '#/parameters/ClientId'
        - name: upload_info
          in: body
          required: true
          schema:
            $ref: '#/definitions/EmailPackage'
      responses:
        200:
          description: The emails were successfully uploaded from the Lokole.
        403:
          description: Request from unregistered client.

parameters:

  ClientId:
    name: client_id
    in: path
    required: true
    description: Id of the Lokole client.
    type: string

definitions:

  EmailPackage:
    properties:
      resource_id:
        description: Id of the resource containing the emails (gzip jsonl file).
        type: string
      resource_container:
        description: Container where the resource containing emails can be found.
        type: string
      resource_type:
        description: The provider where the resource containing emails can be found.
        type: string
        enum: [ 'azure-blob' ]
    required:
     - resource_id
     - resource_container
     - resource_type

