swagger: '2.0'

info:
  title: Opwen Cloudserver Email API.
  version: '0.1'

basePath: '/api/email/sendgrid'

paths:

  '/{client_id}':

    post:
      operationId: opwen_email_server.integration.connexion.email_receive
      summary: Webhook listening to emails received via Sendgrid.
      consumes:
        - multipart/form-data
      parameters:
        - $ref: '#/parameters/ClientId'
        - name: email
          description: Email represented as a MIME string.
          type: string
          in: formData
          required: true
      responses:
        200:
          description: The email was successfully received. No need to retry it.
        403:
          description: Request from unregistered client.

parameters:

  ClientId:
    name: client_id
    in: path
    required: true
    description: Id of the Lokole client.
    type: string
