swagger: '2.0'

info:
  title: Opwen Cloudserver Email API.
  version: '0.1'

basePath: '/job/email/outbound/send'

paths:

  '/':

    post:
      operationId: opwen_email_server.api.send_outbound_emails.send
      summary: Queue-triggered endpoint to send an outbound email.
      consumes:
        - application/json
      parameters:
        - name: resource_id
          description: The id of the email to send.
          type: string
          in: body
          required: true
      responses:
        200:
          description: The email was sent.
