swagger: '2.0'

info:
  title: Opwen Cloudserver Email API.
  version: '0.1'

basePath: '/job/email/client/store'

paths:

  '/':

    post:
      operationId: opwen_email_server.api.store_written_client_emails.store
      summary: Queue-triggered endpoint to store a client email.
      consumes:
        - application/json
      parameters:
        - name: resource_id
          description: The id of the email to store.
          type: string
          in: body
          required: true
      responses:
        200:
          description: The email was stored.
