swagger: '2.0'

info:
  title: Opwen Cloudserver Email API.
  version: '0.1'

basePath: '/job/email/client/store'

paths:

  '/':

    post:
      operationId: opwen_email_server.api.store_written_client_emails.store
      summary: Queue-triggered endpoint to store a client email.
      consumes:
        - application/json
      parameters:
        - name: message
          in: body
          required: true
          schema:
            type: object
            required:
              - resource_id
            properties:
              resource_id:
                type: string
                description: The id of the email to store.
      responses:
        200:
          description: The email was stored.
