swagger: '2.0'

info:
  title: Opwen Cloudserver Email API.
  version: '0.1'

basePath: '/job/email/inbound/store'

paths:

  '/{resource_id}':

    post:
      operationId: opwen_email_server.api.store_inbound_emails.store
      summary: Queue-triggered endpoint to store an inbound email.
      parameters:
        - name: resource_id
          in: path
          required: true
          type: string
          description: The id of the email to process.
      responses:
        200:
          description: The email was stored.
