version: '3.4'

x-shared-secret-environment:
  &shared-secret-environment
  environment:
    DOTENV_SECRETS: azure;cloudflare;users;sendgrid
    LOKOLE_STORAGE_PROVIDER: AZURE_BLOBS
    LOKOLE_QUEUE_BROKER_SCHEME: azureservicebus
  secrets:
    - azure
    - cloudflare
    - users
    - sendgrid

services:

  api:
    <<: *shared-secret-environment

  worker:
    <<: *shared-secret-environment

secrets:
  azure:
    file: ../secrets/azure.env
  cloudflare:
    file: ../secrets/cloudflare.env
  users:
    file: ../secrets/users.env
  sendgrid:
    file: ../secrets/sendgrid.env
