version: '3.4'

services:

  statuspage:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - node_modules:/app/opwen_statuspage/node_modules
      - ./opwen_statuspage:/app/opwen_statuspage

  api:
    command: ["/app/docker/docker-entrypoint-dev.sh", "/app/docker/app/run-gunicorn.sh"]
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      LOKOLE_RANDOM_SEED: "42"
    volumes:
      - ./opwen_email_server:/app/opwen_email_server

  worker:
    command: ["/app/docker/docker-entrypoint-dev.sh", "/app/docker/app/run-celery.sh"]
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      LOKOLE_RANDOM_SEED: "42"
    volumes:
      - ./opwen_email_server:/app/opwen_email_server

  webapp:
    command: ["/app/docker/docker-entrypoint-dev.sh", "/app/docker/client/run-gunicorn.sh"]
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
      - ./opwen_email_client:/app/opwen_email_client
      - ./opwen_email_server:/app/opwen_email_server

  client:
    command: ["/app/docker/docker-entrypoint-dev.sh", "/app/docker/client/run-lokole.sh"]
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      OPWEN_REMOTE_RESOURCE_CONTAINER: compressedpackages
      OPWEN_REMOTE_ACCOUNT_NAME: ${AZURITE_ACCOUNT}
      OPWEN_REMOTE_ACCOUNT_KEY: ${AZURITE_KEY}
      OPWEN_REMOTE_ACCOUNT_HOST: ${AZURITE_HOST}
      OPWEN_REMOTE_ACCOUNT_SECURE: ${AZURITE_SECURE}
      OPWEN_CLIENT_NAME: developer1
      OPWEN_CLIENT_ID: bdd640fb-0667-1ad1-1c80-317fa3b1799d
      LOKOLE_ADMIN_NAME: admin
      LOKOLE_ADMIN_PASSWORD: lokole1Admin
    volumes:
      - ./opwen_email_client:/app/opwen_email_client
      - ./opwen_email_server:/app/opwen_email_server

volumes:
  node_modules:
