version: '3.4'

x-shared-secret-environment:
  &shared-secret-environment
  environment:
    DOTENV_SECRETS: azure;cloudflare;users;sendgrid
    LOKOLE_STORAGE_PROVIDER: AZURE_BLOBS
    LOKOLE_QUEUE_BROKER_SCHEME: azureservicebus
    LOKOLE_EMAIL_SERVER_AZURE_BLOBS_HOST:
    LOKOLE_EMAIL_SERVER_AZURE_BLOBS_SECURE: "True"
    LOKOLE_EMAIL_SERVER_AZURE_TABLES_HOST:
    LOKOLE_EMAIL_SERVER_AZURE_TABLES_SECURE: "True"
    LOKOLE_CLIENT_AZURE_STORAGE_HOST:
    LOKOLE_CLIENT_AZURE_STORAGE_SECURE: "True"
    LOKOLE_EMAIL_SERVER_APPINSIGHTS_HOST:
  secrets:
    - azure
    - cloudflare
    - users
    - sendgrid

services:

  api:
    <<: *shared-secret-environment

  worker:
    <<: *shared-secret-environment

secrets:
  azure:
    file: ./secrets/azure.env
  cloudflare:
    file: ./secrets/cloudflare.env
  users:
    file: ./secrets/users.env
  sendgrid:
    file: ./secrets/sendgrid.env
