domain: mailserver.lokole.ca

version:
  imageRegistry: ascoderu
  dockerTag: latest

server:
  serverWorkers: 2

worker:
  queueWorkers: 1

logging:
  level: DEBUG

letsencrypt:
  email: ascoderu.opwen@gmail.com
  url: https://acme-v02.api.letsencrypt.org/directory
