name: Unit tests & Linters

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - run: |
          make \
            -e BUILD_TARGET=runtime \
            -e LOKOLE_SENDGRID_KEY= \
            -e LOKOLE_QUEUE_BROKER_SCHEME= \
            ci build verify-build
      - run: bash <(curl -s https://codecov.io/bash)
        if: ${{ success() }}
